version: '3'

services:
  flasto-service:
    container_name: flasto-service
    image: flasto-service:1.0
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "5678:5678"
    volumes:
      - .:/opt/flasto-service
