from .sql import (
    MEMBER_INFO,
    COUPON_INFO,
    COUPON_INFO_WITH_AMOUNT,
    CML_CONSUMPTION_INFO,
    MEMBER_GROUPING_DETAIL,
    MEMBER_GROUPING_COUNT,
    MEMBER_GROUPING_DETAIL_CSV,
    MEMBER_GROUPING_NO_LIST,
)
