from .query_crm_member_total_income_report_data import SQL_CRM_MEMBER_TOTAL_INCOME_REPORT_DATA
from .query_crm_member_nowbefore_income_report_data import SQL_CRM_MEMBER_NOWBEFORE_INCOME_REPORT_DATA
from .query_crm_member_newold_income_report_data import SQL_CRM_MEMBER_NEWOLD_INCOME_REPORT_DATA
from .query_crm_member_level_income_report_data import SQL_CRM_MEMBER_LEVEL_INCOME_REPORT_DATA
from .query_crm_member_muldim_income_report_data import SQL_CRM_MEMBER_MULDIM_INCOME_REPORT_DATA