from .query_crm_total_income_report_data import SQL_CRM_TOTAL_INCOME_REPORT_DATA
from .query_crm_member_nowbefore_income_report_data import SQL_CRM_MEMBER_NOWBEFORE_INCOME_REPORT_DATA
from .query_crm_member_newold_income_report_data import SQL_CRM_MEMBER_NEWOLD_INCOME_REPORT_DATA
from .query_crm_member_level_income_report_data import SQL_CRM_MEMBER_LEVEL_INCOME_REPORT_DATA
from .query_crm_member_muldim_income_report_data import SQL_CRM_MEMBER_MULDIM_INCOME_REPORT_DATA
from .query_crm_daily_report_data import SQL_CRM_DAILY_REPORT_DATA
from .query_crm_member_amount_detail_data import SQL_CRM_MEMBER_AMOUNT_DETAIL_DATA