from .dtype_crm_report_center_data import (
    DTYPE_CRM_DAILY_REPORT_DATA,
)
from .dtype_crm_total_income_data import (
    DTYPE_CRM_TOTAL_INCOME_REPORT_DATA,
    DTYPE_CRM_TOTAL_DAILY_INCOME_DETAIL_DATA,
    DTYPE_CRM_TOTAL_MONTHLY_INCOME_DETAIL_DATA,
)
from .dtype_crm_member_income_data import (
    DTYPE_CRM_MEMBER_NOWBEFORE_INCOME_REPORT_DATA,
    DTYPE_CRM_MEMBER_NEWOLD_INCOME_REPORT_DATA,
    DTYPE_CRM_MEMBER_MULDIM_INCOME_REPORT_DATA,
    DTYPE_CRM_MEMBER_LEVEL_INCOME_REPORT_DATA,
    DTYPE_CRM_MEMBER_REGISTER_PROPORTION_REPORT_DATA,
)
from .dtype_crm_member_asset_data import (
    DTYPE_MEMBER_AMOUNT_DETAIL_DATA,
)
