DAILY = {
    'sales_area': str,
    'city': str,
    'store_code': str,
    'member_type': str,
    'sales_amount': float,
    'sales_amount_proportion': float,
    'sales_amount_proportion_total': float,
    'last_year_same_time_sales_amount': float,
    'like_for_like_sales_growth': float,
    'sales_item_quantity': int,
    'discount_rate': float,
    'member_amount': int,
    'past_12_month_remain_member_amount': int,
    'second_trade_rate': float,
    'new_vip_member_amount': int,
    'new_normal_member_amount': int,
    'upgraded_member_amount': int,
    'store_amount': int,
    'member_amount_per_store': float,
    'sales_amount_per_member': float,
    'sales_item_quantity_per_member': float,
    'su_per_member': float,
    'order_amount_per_member': float
}
