version: '3'

services:
  flasto-service-dev:
    container_name: flasto-service-dev
    image: flasto-service-dev:1.1.0
    ports:
      - "18802:5678"
    volumes:
      - /var/log/flasto-service-dev:/opt/flasto-service/query_service/log
      - /var/www/excel/crm-test:/opt/flasto-service/query_service/tmp
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
