FROM python:3.6-slim
MAINTAINER youngsyang@outlook.com
WORKDIR /opt/flasto-service
COPY ./requirements.txt ./
RUN pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir -r requirements.txt