version: '3'

services:
  flasto-service-dev:
    container_name: flasto-service-dev
    image: flasto-service-dev:1.1.0
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "18802:5678"
    volumes:
      - ..:/opt/flasto-service
