version: '3'

services:
  flasto-service:
    build:
      context: ../
      dockerfile: Dockerfile
    image: flasto-service:1.1.0
    container_name: flasto-service
    ports:
      - "5678:5678"
    volumes:
      - /var/log/flasto-service:/opt/flasto-service/query_service/log
      - /var/www/excel/crm-test:/opt/flasto-service/query_service/tmp
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

networks:
  default:
    external:
      name: emr_gw_redis

