version: '3'

services:
  flasto-service-dev:
    container_name: flasto-service-dev
    image: flasto-service-dev:1.1.0
    ports:
      - "5678:5678"
    volumes:
      - ../query_service/log:/opt/flasto-service/query_service/log
      - ../query_service/tmp:/opt/flasto-service/query_service/tmp
